### ISSUE TITLE
Correct way to make new api calls? 

### ISSUE THREAD

**Issue by pjatx** [Shopify/shopify-node-app#123]
Hey Guys, 

A bit of a node N00B and trying to set up a simple carrier service  that will provide different shipping rates to our wholesale customers. 

To accomplish this, I need to loop through the items in the cart and check to see if see if their tags array contains a specific tag. I've been really struggling with making API calls within a new post route I've set up, mainly because I'm not sure where to grab the access token and it's not super clear in the docs (or maybe just my n00bness). 

What's the correct way to set up a backend API properly call using the shop credentials? Currently doing something like this, but both shopDomain and accessToken are undefined. Have also tried different flavors of grabbing it from the session without luck. Any help would be appreciated!

`request.session.accessToken`
`req.session.accessToken`

```
app.post('/rates', jsonParser, function (request, res) {

  const shopify = new ShopifyAPIClient({ shopName: shopDomain, accessToken: accessToken });
  shopify.product.get(1234)

  // Do more stufff

});
```

Ended up going the private route, but still curious on the correct way to do this.

**Comment by Avidexp** [comment]
I've been looking for a similar answer for a while. Let me know if you find out something! I can get it hitting my custom URL for rates, but it never renders the response of my api as valid rates to choose from...

**Comment by pjatx** [comment]
@Avidexp Did you register the carrier service first? 

https://help.shopify.com/en/api/reference/shipping_and_fulfillment/carrierservice#create

**Comment by Avidexp** [comment]
Yes sir I did,

I ended up getting it to work. I had my rates in just an array, not an
array wrapped in an object.

Ex.

[{
'service_name': 'Globaltranz Fast',
'description': 'fastest rate',
'service_code': 'GTZ',
'total_price': '100000.80',
'currency': 'USD',
'min_delivery_date': '2018-07-28 14:48:45 -0400',
'max_delivery_date': '2018-07-30 14:48:45 -0400'
}

rather than
{
"rates":[{
'service_name': 'Globaltranz Fast',
'description': 'fastest rate',
'service_code': 'GTZ',
'total_price': '100000.80',
'currency': 'USD',
'min_delivery_date': '2018-07-28 14:48:45 -0400',
'max_delivery_date': '2018-07-30 14:48:45 -0400'
}
}

**Comment by pjatx** [comment]
Ah the little things : ) Did you by chance use this library? Curious to see what your code looks like. I ended up writing mine with the node express library instead as a private app vs a public one.

**Comment by Avidexp** [comment]
So I actually made a public one doing the same thing with express lol. I found it was easier to eliminate some of the noise, and just try to build it out one step at a time, rather than using the template.

I can create/edit/delete carrier services no problem now, and I can pass back static rate information that gets procesed by shopify so the user can pick the rate. The only problem I'm having now, is I cant find the shopping cart information in the requests I get from shopify lol. 

I'm using simple express API like:
  app.get('/shopify/callback', (req, res) => {}

Yet req.body always comes out empty. Have you experienced this as well?

**Comment by pjatx** [comment]
I can't quite remember now, but I can show you what I'm doing to loop through the cart items. I'd recommend using bodyParser.

```
...
// Set vars and imports etc...
...

const bodyParser = require('body-parser');

// Create application/json parser
var jsonParser = bodyParser.json()

// Shipping Carrier Service
app.post('/rates', jsonParser, function (req, res) {

...
/// rates logic here
...

  // Save rates request
  var ratesReq = req.body;
  var products = ratesReq['rate']['items']

});
```

**Comment by Avidexp** [comment]
bodyParser!! 

Can't believe I forgot that! You're amazing pjatx, thanks man!!

**Comment by pjatx** [comment]
No worries man! Glad I could be helpful. I beat my head on this project for a long time : )

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
