### ISSUE TITLE
Address Server Side Rendering

### ISSUE THREAD

**Issue by TheMallen** [Shopify/shopify-node-app#35]
We should either get SSR working or address why it's not important for an embedded app in our readme (or at least remove the checkbox).

**Comment by sbstnmsch** [comment]
Upvote: I got SSR working but have problems getting the `EmbeddedApp` component to work - because server-side there is now window object. Fair enough. I just dropped it for now - lacking support of IFRAME messaging causing my app to sometimes break out the IFRAME. Would be nice to have a SSR solution or documentation for the frame messaging.

**Comment by nwtn** [comment]
Closing because this project is now deprecated.
