### ISSUE TITLE
"Your webhook is failing" emails

### ISSUE THREAD

**Issue by theptrk** [Shopify/shopify-node-app#98]
I've been actively developing an app using `ngrok` and have had multiple public urls. 

I believe webhooks are automatically created and now I have a ton of emails saying that webhooks to those now expired urls are still receiving requests. 

![screen shot 2018-03-14 at 9 46 57 pm](https://user-images.githubusercontent.com/5618025/37444903-9567035e-27d1-11e8-8b3d-aa5e63adb31c.png)

I've checked the stores settings under `Settings > Notifications > Webhooks` and it doesn't list any registered webhooks

How do I unregister these development webhooks?

**Comment by BarryCarlyon** [comment]
`Settings > Notifications > Webhooks` only shows store/admin created webhooks.

To unregister development webhooks either just ride the email spam and let shopify self nerf.

Or manually call the webhooks list/delete endpoint as described here:

https://help.shopify.com/api/reference/webhook

Consider adding a boot function to your app that

- GET /admin/webhooks.json

And then

- DELETE /admin/webhooks/#{id}.json

Each webhook returned by the get.

Since you auth with Client/Auth, you'd first have to jump the oAuth loop and then do a list and delete before calling the `registerWebhook` in `afterAuth`

**Comment by theptrk** [comment]
Thanks!
